AllCops:
  NewCops: disable
  Exclude:
    - 'bin/webpack'
    - 'bin/webpack-dev-server'
    - 'bin/bundle'
    - 'db/migrate/*'
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false